title = "Citadel"
description = "Self-hosted mini search engine"
source = "https://github.com/niljimeno/citadel-janet"
theme = "nein"


[[sites]]
name = "AnalogNowhere"
url = "https://analognowhere.com"
description = "Unix-themed fan-fiction."
tags = ["Art", "Unix", "Plan 9"]

[[sites]]
name = "Based Cooking"
url = "https://based.cooking"
description = "Cooking site that doesn't suck."
tags = ["Cooking"]

[[sites]]
name = "Cat-v.org"
url = "https://cat-v.org"
description = "Random Contrarian Insurgent Organization"
tags = ["Unix", "Plan 9"]

[[sites]]
name = "Cidoku"
url = "https://cidoku.net"
description = "Retro personal webpage."
tags = ["Art", "Blog", "Flash", "Music"]

[[sites]]
name = "Dan's website"
description = "Author of the 'Plan 9 Desktop Guide' blog post."
url = "https://pspodcasting.net/dan"
tags = ["Art", "Blog", "Unix", "Plan 9"]

[[sites]]
name = "Eshan Ramesh"
description = "Fun lisp blog"
url = "https://esrh.me"
tags = ["Blog", "Lisp", "Programming"]

[[sites]]
name = "Frtv"
url = "https://ftrv.se"
tags =  ["Blog", "Plan 9"]

[[sites]]
name = "Download Free Kromer"
url = "https://kromercoin.com"
description = "Spamton-themed Neocities site."
tags = ["Art"]

[[sites]]
name = "Lainchan"
url = "https://lainchan.org"
description = "Lain-themed imageboard."
tags = ["Social", "DIY", "Lisp", "Programming"]

[[sites]]
name = "Landchad"
url = "https://landchad.net"
description = "Minimal self-hosting articles. Very high quality."
tags = ["Unix"]

[[sites]]
name = "Luke Smith"
url = "https://lukesmith.xyz"
description = "Luke Smith's website - high quality video rants and blog posts."
tags = ["Blog", "Unix", "Videos", "Privacy"]

[[sites]]
name = "Max Bernstein"
url = "https://bernsteinbear.com"
tags = ["Blog", "Lisp", "Programming"]

[[sites]]
name = "Nein"
url = "https://nein.triapul.cz"
tags = ["Unix", "Plan 9"]

[[sites]]
name = "NOPENOPENOPE"
url = "https://nopenopenope.net"
tags = ["Music", "Blog", "Plan 9"]

[[sites]]
name = "news.olano.dev"
url = "https://news.olano.dev"
description = "News feed from different blogs."
tags = ["Blog", "Programming"]

[[sites]]
name = "Nic Olas"
url = "https://nic-olas.me"
description = "Luke Smith's evil clone (does Lisp and Emacs)."
tags = ["Lisp", "Programming", "Unix", "Videos"]

[[sites]]
name = "Nowhere"
url = "https://nowhere.moe"
description = "An internet corner."
tags = ["Social", "Privacy", "Psychology"]

[[sites]]
name = "Torpus"
url = "https://torpus.info"
description = "Weeb blog on psychology and our technological dystopia."
tags = ["Blog", "Psychology"]

[[sites]]
name = "Orib"
url = "https://orib.dev"
description = "Golang programming blog."
tags = ["Programming"]

[[sites]]
name = "Pepper & Carrot"
url = "https://peppercarrot.com"
description = "Free and open source webcomic."
tags = ["Art"]

[[sites]]
name = "Plan 9 Wiki"
url = "https://plan9.io/wiki/plan9"
description = "Plan 9's official wiki."
tags = ["Plan 9"]

[[sites]]
name = "Sebastiano Tronto"
url = "https://sebastiano.tronto.net"
tags = ["Blog", "Programming", "Unix"]

[[sites]]
name = "Spyware Watchdog"
url = "https://spyware.neocities.org"
description = "Articles on spyware analysis."
tags = ["Social", "Privacy", "Search Engine"]

[[sites]]
name = "Suckless"
url = "https://suckless.org"
description = "Free software organization."
tags = ["Unix"]

[[sites]]
name = "Wiby"
url = "https://wiby.me"
description = "Retro search engine."
tags = ["Search engine"]

[[sites]]
name = "Wired-7"
url = "https://wired-7.org"
description = "Cyberpunk hispanic imageboard."
tags = ["Social"]

[[sites]]
name = "9front"
url = "https://9front.org"
description = "The plan fell off. Join the revolution front."
tags = ["Plan 9"]

[[sites]]
name = "9lab"
url = "https://9lab.org/blog/plan9"
description = "Plan 9 blog."
tags = ["Blog", "Plan 9"]

[[sites]]
name = "Niliara.net"
url = "https://niliara.net"
description = "My site."

[[sites]]
name = "Dig Deeper"
url = "https://digdeeper.club/"
tags = ["Psychology", "Unix", "Privacy"]

[[sites]]
name = "Merveilles"
url = "https://merveilles.town"
description = "Mastodon instance (hosting AnalogNowhere and Devine Lu Linvega)."
tags = ["Social"]

[[sites]]
name = "Lainzine"
url = "https://lainzine.org/"
description = "Cyberpunk magazine based themed on Serial Experiments Lain."
tags = ["DIY"]

[[sites]]
name = "The Lantern Darknet Project"
url = "http://lantern6vrwheap4iahuktz3jtwvovrzhxgwgzvrvp46brdzzekxibqd.onion/"
description = "Self-hosted darknet search engine."
tags = ["Search Engine", "Privacy"]

[[sites]]
name = "Dan-Simon Myrlands personal blog space"
url = "https://pspodcasting.net/dan/blog/index.html"
description = "Author of the Plan 9 Desktop User Guide."
tags = ["Blog", "Unix", "Plan 9"]

[[sites]]
name = "Michdev"
url = "https://michdev.nekoweb.org/"
description = "Terminal-like designed website."
tags = ["Art"]

[[sites]]
name = "Neocities.org"
url = "https://neocities.org/"
description = "Home of the indie web. Host your personal homepage for free!"
tags = ["Art", "Search Engine"]

[[sites]]
name = "Nekoweb.org"
url = "https://nekoweb.org/"
description = "I heard it's like Neocities but better."
tags = ["Art", "Search Engine"]

[[sites]]
name = "Cock.li"
url = "https://cock.li"
description = "It's email with cocks!"
tags = ["Social", "Privacy"]

[[sites]]
name = "Dangerous opinions"
url = "https://dangeru.us/"
description = "Cyberpunk-themed social media page inspired on Va-11 Hall-a."
tags = ["Social"]

[[sites]]
name = "Devine Lu Linvega"
url = "https://wiki.xxiivv.com/"
description = "Creator of UXN and a lot of cool nerdy projects!"
tags = ["Art", "Programming"]

[[sites]]
name = "100 Rabbits"
url = "https://100r.co"
description = "Organization of hackers and artists, home of UXN."
tags = ["Art", "Programming"]

[[sites]]
name = "Cyberia Comuputer Club"
url = "https://cyberia.club/"
description = "A kind and amazing hacker collective centered in Minnesota with global friends."
tags = ["Social"]
